---
- set_fact: matching_zones='{{ (item.zones.keys()|list | intersect(group_names)) }}'
  with_items: '{{ users }}'

- name: Create user
  include: user.yml
  when: (item.zones.keys()|list | intersect(group_names)) | length > 0
  with_items: '{{ users }}'
