---
- name: Get info on docker host
  docker_host_info:
  register: host_result

#- set_fact: host_info='{{ host_result.host_info.Swarm }}'
#  when: 'host_result.host_info.Swarm.LocalNodeState == "active"'

- name: Get info on Docker Swarm and filtered list of registered nodes
  docker_swarm_info:
  register: swarm_result
  when: 'host_result.host_info.Swarm.LocalNodeState == "active"'

#- set_fact: swarm_info='{{ swarm_result }}'
#  when: 'host_result.host_info.Swarm.LocalNodeState == "active"'



#- debug:
#    var: host_result
#
#- debug:
#    var: swarm_result
