---
- name: Init a new swarm with default parameters
  docker_swarm:
    advertise_addr: '{{ ansible_eth1.ipv4.address }}'
    state: present

- name: Get info on docker host
  docker_host_info:
  register: host_result

- name: Get info on Docker Swarm
  docker_swarm_info:
  register: swarm_result
